"""empty message

Revision ID: e92b05a86488
Revises: 
Create Date: 2022-08-29 00:58:12.772618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92b05a86488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_index(op.f('ix_equipment_properties'), 'equipment', ['properties'], unique=False)
    op.create_index(op.f('ix_equipment_timestamp'), 'equipment', ['timestamp'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.Column('uses', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_name'), 'material', ['name'], unique=True)
    op.create_index(op.f('ix_material_properties'), 'material', ['properties'], unique=False)
    op.create_index(op.f('ix_material_timestamp'), 'material', ['timestamp'], unique=False)
    op.create_index(op.f('ix_material_uses'), 'material', ['uses'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.String(length=15), nullable=False),
    sa.Column('duration', sa.String(length=3), nullable=False),
    sa.Column('client', sa.Text(), nullable=False),
    sa.Column('start_year', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budget'), 'project', ['budget'], unique=False)
    op.create_index(op.f('ix_project_client'), 'project', ['client'], unique=False)
    op.create_index(op.f('ix_project_description'), 'project', ['description'], unique=False)
    op.create_index(op.f('ix_project_duration'), 'project', ['duration'], unique=False)
    op.create_index(op.f('ix_project_location'), 'project', ['location'], unique=False)
    op.create_index(op.f('ix_project_start_year'), 'project', ['start_year'], unique=False)
    op.create_index(op.f('ix_project_timestamp'), 'project', ['timestamp'], unique=False)
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pix', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_pix'), 'image', ['pix'], unique=False)
    op.create_index(op.f('ix_image_timestamp'), 'image', ['timestamp'], unique=False)
    op.create_table('sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_doc'), 'sheet', ['doc'], unique=False)
    op.create_index(op.f('ix_sheet_timestamp'), 'sheet', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sheet_timestamp'), table_name='sheet')
    op.drop_index(op.f('ix_sheet_doc'), table_name='sheet')
    op.drop_table('sheet')
    op.drop_index(op.f('ix_image_timestamp'), table_name='image')
    op.drop_index(op.f('ix_image_pix'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_index(op.f('ix_project_timestamp'), table_name='project')
    op.drop_index(op.f('ix_project_start_year'), table_name='project')
    op.drop_index(op.f('ix_project_location'), table_name='project')
    op.drop_index(op.f('ix_project_duration'), table_name='project')
    op.drop_index(op.f('ix_project_description'), table_name='project')
    op.drop_index(op.f('ix_project_client'), table_name='project')
    op.drop_index(op.f('ix_project_budget'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_material_uses'), table_name='material')
    op.drop_index(op.f('ix_material_timestamp'), table_name='material')
    op.drop_index(op.f('ix_material_properties'), table_name='material')
    op.drop_index(op.f('ix_material_name'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_equipment_timestamp'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_properties'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
